version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/philipjonsen/xuperchain"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"